"""Autogenerated ML Agent wrapper for DengueAgent.

This file was generated by the CSV Builder Script from
dengue_diseases_dataset.csv. Feature metadata and clinical class labels
were authored by hand after generation — do not regenerate this file
without preserving them.
"""

from pathlib import Path
from typing import Any

from services.ml_mcp_server.models._agent_factory import AgentConfig, DynamicMLAgent

# --- 1. Paths & Configuration ---
_ARTIFACT_PATH = Path(__file__).parent.parent / "artifacts" / "dengue_xgb_dynamic.joblib"

_FEATURE_METADATA: dict[str, dict[str, Any]] = {
    "age": {
        "label": "Age",
        "detail": "Current age in years.",
        "aliases": ["age", "나이", "살", "세"],
        "unit": "years",
        "field_type": "number",
    },
    "hemoglobin": {
        "label": "Hemoglobin",
        "detail": "Hemoglobin level from a complete blood count (CBC).",
        "aliases": ["hemoglobin", "hgb", "헤모글로빈"],
        "unit": "g/dL",
        "field_type": "number",
    },
    "wbc_count": {
        "label": "White blood cell count",
        "detail": "Total leukocyte count from a complete blood count (CBC). Leukopenia is common in dengue.",
        "aliases": ["wbc", "white blood cell count", "백혈구"],
        "unit": "×10⁹/L",
        "field_type": "number",
    },
    "differential_count": {
        "label": "Differential count",
        "detail": "Differential white blood cell index from the CBC. Encoded as a small integer in the source dataset.",
        "aliases": ["differential", "diff count"],
        "field_type": "number",
    },
    "rbc_count": {
        "label": "Red blood cell count",
        "detail": "Total red blood cell count from a complete blood count (CBC).",
        "aliases": ["rbc", "red blood cell count", "적혈구"],
        "unit": "×10¹²/L",
        "field_type": "number",
    },
    "platelet_count": {
        "label": "Platelet count",
        "detail": "Platelet count from a complete blood count (CBC). Thrombocytopenia is a hallmark of dengue.",
        "aliases": ["platelets", "platelet count", "혈소판"],
        "unit": "/μL",
        "field_type": "number",
    },
    "pdw": {
        "label": "Platelet distribution width",
        "detail": "Variability in platelet size from a CBC.",
        "aliases": ["pdw", "platelet distribution width"],
        "unit": "%",
        "field_type": "number",
    },
    "gender_Female": {
        "label": "Sex: Female",
        "detail": "1 if the patient is female, 0 otherwise.",
        "aliases": ["female", "gender female", "여성"],
        "field_type": "yes_no",
    },
    "gender_Male": {
        "label": "Sex: Male",
        "detail": "1 if the patient is male, 0 otherwise.",
        "aliases": ["male", "gender male", "남성"],
        "field_type": "yes_no",
    },
}

_DENGUEAGENT_CONFIG = AgentConfig(
    agent_name="predict_dengue",
    description=(
        "Binary classifier for dengue from a complete blood count panel + "
        "demographics. Inputs are 9 CBC-derived fields plus age and sex."
    ),
    version="1.0.0-auto",
    artifact_path=_ARTIFACT_PATH,
    feature_names=['age', 'hemoglobin', 'wbc_count', 'differential_count', 'rbc_count', 'platelet_count', 'pdw', 'gender_Female', 'gender_Male'],
    target_classes=['negative', 'dengue_positive'],
    trained_on_desc="dengue_diseases_dataset.csv — XGBoost K-fold ensemble",
    feature_metadata=_FEATURE_METADATA,
    n_splits=5
)

# --- 2. MCP Server Agent Class ---
class DengueAgent(DynamicMLAgent):
    """Dynamic binary classifier for dengue."""

    def __init__(self) -> None:
        super().__init__(_DENGUEAGENT_CONFIG)

    def sample_inputs(self) -> dict[str, Any]:
        """A representative sample case extracted during the build process."""
        return {
        "age": 43.0,
        "hemoglobin": 12.6,
        "wbc_count": 2200.0,
        "differential_count": 1.0,
        "rbc_count": 1.0,
        "platelet_count": 62000.0,
        "pdw": 11.0,
        "gender_Female": 0.0,
        "gender_Male": 1.0
        }
