"""Autogenerated ML Agent wrapper for HeartFailureAgent.

This file was generated by the CSV Builder Script from
heart_failure_clinical_records_dataset.csv. Feature metadata and clinical
class labels were authored by hand after generation — do not regenerate
this file without preserving them.
"""

from pathlib import Path
from typing import Any

from services.ml_mcp_server.models._agent_factory import AgentConfig, DynamicMLAgent

# --- 1. Paths & Configuration ---
_ARTIFACT_PATH = Path(__file__).parent.parent / "artifacts" / "heart_failure_xgb_dynamic.joblib"

_FEATURE_METADATA: dict[str, dict[str, Any]] = {
    "age": {
        "label": "Age",
        "detail": "Current age in years.",
        "aliases": ["age", "나이", "살", "세"],
        "unit": "years",
        "field_type": "number",
    },
    "anaemia": {
        "label": "Anaemia",
        "detail": "Reduced red blood cells / haemoglobin (1 = yes, 0 = no).",
        "aliases": ["anaemia", "anemia", "빈혈"],
        "field_type": "yes_no",
    },
    "creatinine_phosphokinase": {
        "label": "CPK enzyme",
        "detail": "Creatine phosphokinase level in the blood — an enzyme released when muscle (including heart) is damaged.",
        "aliases": ["cpk", "creatine kinase", "creatinine phosphokinase", "CK"],
        "unit": "mcg/L",
        "field_type": "number",
    },
    "diabetes": {
        "label": "Diabetes",
        "detail": "Whether the patient has been diagnosed with diabetes (1 = yes, 0 = no).",
        "aliases": ["diabetes", "당뇨", "당뇨병"],
        "field_type": "yes_no",
    },
    "ejection_fraction": {
        "label": "Ejection fraction",
        "detail": "Percentage of blood the left ventricle pumps out per contraction. Below ~40% suggests reduced systolic function.",
        "aliases": ["ejection fraction", "ef", "박출률"],
        "unit": "%",
        "field_type": "number",
    },
    "high_blood_pressure": {
        "label": "Hypertension",
        "detail": "Whether the patient has a clinical diagnosis of high blood pressure (1 = yes, 0 = no).",
        "aliases": ["hypertension", "high blood pressure", "고혈압"],
        "field_type": "yes_no",
    },
    "platelet_count": {
        "label": "Platelet count",
        "detail": "Platelets in the blood (a complete blood count line item).",
        "aliases": ["platelets", "platelet count", "혈소판"],
        "unit": "kiloplatelets/mL",
        "field_type": "number",
    },
    "creatinine": {
        "label": "Serum creatinine",
        "detail": "Kidney function marker from a basic metabolic panel blood test.",
        "aliases": ["creatinine", "serum creatinine", "크레아티닌"],
        "unit": "mg/dL",
        "field_type": "number",
    },
    "sodium": {
        "label": "Serum sodium",
        "detail": "Blood sodium level from a basic metabolic panel.",
        "aliases": ["sodium", "Na", "나트륨"],
        "unit": "mEq/L",
        "field_type": "number",
    },
    "gender": {
        "label": "Sex (male)",
        "detail": "1 if the patient is male, 0 otherwise.",
        "aliases": ["gender", "sex", "남성", "성별"],
        "field_type": "yes_no",
    },
    "smoking": {
        "label": "Current smoker",
        "detail": "Whether the patient currently smokes (1 = yes, 0 = no).",
        "aliases": ["smoking", "smoker", "흡연"],
        "field_type": "yes_no",
    },
    "time": {
        "label": "Follow-up period",
        "detail": "Days of follow-up after the index hospitalization. The model uses this as a temporal context feature.",
        "aliases": ["follow-up", "follow up days", "추적 기간"],
        "unit": "days",
        "field_type": "number",
    },
}

_HEARTFAILUREAGENT_CONFIG = AgentConfig(
    agent_name="predict_heart_failure",
    description=(
        "Binary classifier for in-follow-up death after a heart-failure "
        "hospitalization. Inputs are 12 commonly recorded clinical fields "
        "(demographics, key labs, ejection fraction, comorbidities)."
    ),
    version="1.0.0-auto",
    artifact_path=_ARTIFACT_PATH,
    feature_names=['age', 'anaemia', 'creatinine_phosphokinase', 'diabetes', 'ejection_fraction', 'high_blood_pressure', 'platelet_count', 'creatinine', 'sodium', 'gender', 'smoking', 'time'],
    target_classes=['survived', 'death_event'],
    trained_on_desc="heart_failure_clinical_records_dataset.csv (n=299) — XGBoost K-fold ensemble",
    feature_metadata=_FEATURE_METADATA,
    n_splits=5
)

# --- 2. MCP Server Agent Class ---
class HeartFailureAgent(DynamicMLAgent):
    """Dynamic binary classifier for heart-failure mortality risk."""

    def __init__(self) -> None:
        super().__init__(_HEARTFAILUREAGENT_CONFIG)

    def sample_inputs(self) -> dict[str, Any]:
        """A representative sample case extracted during the build process."""
        return {
        "age": 75.0,
        "anaemia": 0.0,
        "creatinine_phosphokinase": 582.0,
        "diabetes": 0.0,
        "ejection_fraction": 20.0,
        "high_blood_pressure": 1.0,
        "platelet_count": 265000.0,
        "creatinine": 1.9,
        "sodium": 130.0,
        "gender": 1.0,
        "smoking": 0.0,
        "time": 4.0
        }
