"""Autogenerated ML Agent wrapper for HeartDiseaseAgent.

This file was generated by the CSV Builder Script from heart.csv (the
Cleveland UCI heart disease dataset). Feature metadata and clinical
class labels were authored by hand after generation — do not regenerate
this file without preserving them.
"""

from pathlib import Path
from typing import Any

from services.ml_mcp_server.models._agent_factory import AgentConfig, DynamicMLAgent

# --- 1. Paths & Configuration ---
_ARTIFACT_PATH = Path(__file__).parent.parent / "artifacts" / "heart_disease_xgb_dynamic.joblib"

_FEATURE_METADATA: dict[str, dict[str, Any]] = {
    "age": {
        "label": "Age",
        "detail": "Current age in years.",
        "aliases": ["age", "나이", "살", "세"],
        "unit": "years",
        "field_type": "number",
    },
    "gender": {
        "label": "Sex (male)",
        "detail": "1 if the patient is male, 0 otherwise.",
        "aliases": ["gender", "sex", "남성", "성별"],
        "field_type": "yes_no",
    },
    "cp": {
        "label": "Chest pain type",
        "detail": "Encoded chest-pain category: 0 = typical angina, 1 = atypical angina, 2 = non-anginal pain, 3 = asymptomatic.",
        "aliases": ["chest pain", "cp", "흉통"],
        "field_type": "category",
    },
    "trestbps": {
        "label": "Resting blood pressure",
        "detail": "Resting systolic blood pressure on admission.",
        "aliases": ["resting bp", "trestbps", "수축기혈압"],
        "unit": "mmHg",
        "field_type": "number",
    },
    "cholesterol": {
        "label": "Serum cholesterol",
        "detail": "Total cholesterol from a lipid panel blood test.",
        "aliases": ["cholesterol", "total cholesterol", "콜레스테롤"],
        "unit": "mg/dL",
        "field_type": "number",
    },
    "fbs": {
        "label": "Fasting blood sugar > 120 mg/dL",
        "detail": "1 if fasting blood sugar exceeds 120 mg/dL, else 0.",
        "aliases": ["fbs", "fasting blood sugar", "공복혈당"],
        "field_type": "yes_no",
    },
    "restecg": {
        "label": "Resting ECG result",
        "detail": "Encoded resting ECG finding: 0 = normal, 1 = ST-T wave abnormality, 2 = probable / definite left-ventricular hypertrophy.",
        "aliases": ["resting ecg", "restecg", "심전도"],
        "field_type": "category",
    },
    "thalach": {
        "label": "Maximum heart rate",
        "detail": "Maximum heart rate achieved during an exercise stress test.",
        "aliases": ["max heart rate", "thalach", "최대 심박수"],
        "unit": "bpm",
        "field_type": "number",
    },
    "exang": {
        "label": "Exercise-induced angina",
        "detail": "1 if chest pain was triggered by the exercise stress test, else 0.",
        "aliases": ["exercise angina", "exang"],
        "field_type": "yes_no",
    },
    "oldpeak": {
        "label": "ST depression (oldpeak)",
        "detail": "ST-segment depression induced by exercise relative to rest, in millimeters.",
        "aliases": ["oldpeak", "st depression"],
        "unit": "mm",
        "field_type": "number",
    },
    "slope": {
        "label": "Peak exercise ST slope",
        "detail": "Slope of the peak exercise ST segment: 0 = upsloping, 1 = flat, 2 = downsloping.",
        "aliases": ["slope", "st slope"],
        "field_type": "category",
    },
    "ca": {
        "label": "Major vessels colored on fluoroscopy",
        "detail": "Number of major coronary vessels (0–3) visualized via fluoroscopy.",
        "aliases": ["ca", "vessels", "관상동맥"],
        "field_type": "number",
    },
    "thal": {
        "label": "Thalassemia / thallium scan",
        "detail": "Thallium stress test category: 1 = fixed defect, 2 = normal, 3 = reversible defect.",
        "aliases": ["thal", "thalassemia", "탈륨"],
        "field_type": "category",
    },
}

_HEARTDISEASEAGENT_CONFIG = AgentConfig(
    agent_name="predict_heart_disease",
    description=(
        "Binary classifier for coronary heart disease from the Cleveland UCI "
        "dataset. Inputs are 13 routine cardiac workup fields: demographics, "
        "resting and exercise ECG, lipid panel, and thallium stress test."
    ),
    version="1.0.0-auto",
    artifact_path=_ARTIFACT_PATH,
    feature_names=['age', 'gender', 'cp', 'trestbps', 'cholesterol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal'],
    target_classes=['no_heart_disease', 'heart_disease'],
    trained_on_desc="UCI Cleveland heart disease dataset (heart.csv, n=303) — XGBoost K-fold ensemble",
    feature_metadata=_FEATURE_METADATA,
    n_splits=5
)

# --- 2. MCP Server Agent Class ---
class HeartDiseaseAgent(DynamicMLAgent):
    """Dynamic binary classifier for coronary heart disease risk."""

    def __init__(self) -> None:
        super().__init__(_HEARTDISEASEAGENT_CONFIG)

    def sample_inputs(self) -> dict[str, Any]:
        """A representative sample case extracted during the build process."""
        return {
        "age": 52.0,
        "gender": 1.0,
        "cp": 0.0,
        "trestbps": 125.0,
        "cholesterol": 212.0,
        "fbs": 0.0,
        "restecg": 1.0,
        "thalach": 168.0,
        "exang": 0.0,
        "oldpeak": 1.0,
        "slope": 2.0,
        "ca": 2.0,
        "thal": 3.0
        }
