"""Autogenerated ML Agent wrapper for LiverDiseaseAgent.

This file was generated by the CSV Builder Script from
indian_liver_patient_dataset_ilpd.csv. Feature metadata and clinical
class labels were authored by hand after generation — do not regenerate
this file without preserving them.

Note on target class ordering: the original ILPD target encoded 1 = liver
patient and 2 = non-patient. The CSV builder sorts ([1, 2]) and maps
{1→0, 2→1}. So internally class 0 = liver_disease, class 1 = no_liver_disease.
target_classes preserves this order so downstream readers see the
clinically correct label for predict_proba[:, 1].
"""

from pathlib import Path
from typing import Any

from services.ml_mcp_server.models._agent_factory import AgentConfig, DynamicMLAgent

# --- 1. Paths & Configuration ---
_ARTIFACT_PATH = Path(__file__).parent.parent / "artifacts" / "liver_disease_xgb_dynamic.joblib"

_FEATURE_METADATA: dict[str, dict[str, Any]] = {
    "age": {
        "label": "Age",
        "detail": "Current age in years.",
        "aliases": ["age", "나이", "살", "세"],
        "unit": "years",
        "field_type": "number",
    },
    "total_bilirubin": {
        "label": "Total bilirubin",
        "detail": "Total bilirubin level from a liver function blood panel.",
        "aliases": ["total bilirubin", "tbil", "총빌리루빈"],
        "unit": "mg/dL",
        "field_type": "number",
    },
    "direct_bilirubin": {
        "label": "Direct bilirubin",
        "detail": "Direct (conjugated) bilirubin from a liver function blood panel.",
        "aliases": ["direct bilirubin", "dbil", "직접빌리루빈"],
        "unit": "mg/dL",
        "field_type": "number",
    },
    "alkaline_phosphotase": {
        "label": "Alkaline phosphatase (ALP)",
        "detail": "Enzyme elevated in many liver and biliary conditions; from a liver function blood panel.",
        "aliases": ["alkaline phosphatase", "alp", "ALP"],
        "unit": "IU/L",
        "field_type": "number",
    },
    "alamine_aminotransferase": {
        "label": "ALT",
        "detail": "Alanine aminotransferase (ALT / SGPT) — a liver enzyme on a liver function blood panel.",
        "aliases": ["alt", "sgpt", "alanine aminotransferase"],
        "unit": "IU/L",
        "field_type": "number",
    },
    "aspartate_aminotransferase": {
        "label": "AST",
        "detail": "Aspartate aminotransferase (AST / SGOT) — a liver enzyme on a liver function blood panel.",
        "aliases": ["ast", "sgot", "aspartate aminotransferase"],
        "unit": "IU/L",
        "field_type": "number",
    },
    "total_protiens": {
        "label": "Total protein",
        "detail": "Total protein from a liver function blood panel.",
        "aliases": ["total protein", "total proteins", "총단백"],
        "unit": "g/dL",
        "field_type": "number",
    },
    "albumin": {
        "label": "Albumin",
        "detail": "Serum albumin from a liver function blood panel.",
        "aliases": ["albumin", "알부민"],
        "unit": "g/dL",
        "field_type": "number",
    },
    "albumin_and_globulin_ratio": {
        "label": "Albumin / globulin ratio",
        "detail": "Ratio of albumin to globulin from a liver function blood panel.",
        "aliases": ["a/g ratio", "albumin globulin ratio"],
        "unit": "ratio",
        "field_type": "number",
    },
    "gender_Male": {
        "label": "Sex: Male",
        "detail": "1 if the patient is male, 0 otherwise.",
        "aliases": ["male", "gender male", "남성"],
        "field_type": "yes_no",
    },
}

_LIVERDISEASEAGENT_CONFIG = AgentConfig(
    agent_name="predict_liver_disease",
    description=(
        "Binary classifier for liver disease (ILPD). Inputs are a routine "
        "liver function panel plus age and sex."
    ),
    version="1.0.0-auto",
    artifact_path=_ARTIFACT_PATH,
    feature_names=['age', 'total_bilirubin', 'direct_bilirubin', 'alkaline_phosphotase', 'alamine_aminotransferase', 'aspartate_aminotransferase', 'total_protiens', 'albumin', 'albumin_and_globulin_ratio', 'gender_Male'],
    # Original CSV encoded 1=patient, 2=non-patient. After sorted+mapping the
    # internal class 0 is "liver_disease" and class 1 is "no_liver_disease"
    # — keep that order so predicted_class semantics line up.
    target_classes=['liver_disease', 'no_liver_disease'],
    trained_on_desc="Indian Liver Patient Dataset / ILPD (n=583) — XGBoost K-fold ensemble",
    feature_metadata=_FEATURE_METADATA,
    n_splits=5
)

# --- 2. MCP Server Agent Class ---
class LiverDiseaseAgent(DynamicMLAgent):
    """Dynamic binary classifier for liver disease."""

    def __init__(self) -> None:
        super().__init__(_LIVERDISEASEAGENT_CONFIG)

    def sample_inputs(self) -> dict[str, Any]:
        """A representative sample case extracted during the build process."""
        return {
        "age": 65.0,
        "total_bilirubin": 0.7,
        "direct_bilirubin": 0.1,
        "alkaline_phosphotase": 187.0,
        "alamine_aminotransferase": 16.0,
        "aspartate_aminotransferase": 18.0,
        "total_protiens": 6.8,
        "albumin": 3.3,
        "albumin_and_globulin_ratio": 0.9,
        "gender_Male": 0.0
        }
