"""Autogenerated ML Agent wrapper for SepsisAgent.

This file was generated by the CSV Builder Script from dataset.csv (a
PhysioNet-style sepsis prediction dataset). Feature metadata and clinical
class labels were authored by hand after generation — do not regenerate
this file without preserving them.
"""

from pathlib import Path
from typing import Any

from services.ml_mcp_server.models._agent_factory import AgentConfig, DynamicMLAgent

# --- 1. Paths & Configuration ---
_ARTIFACT_PATH = Path(__file__).parent.parent / "artifacts" / "sepsis_xgb_dynamic.joblib"

_FEATURE_METADATA: dict[str, dict[str, Any]] = {
    "Unnamed: 0": {
        "label": "Row index",
        "detail": "CSV row index artifact (not clinically meaningful — leave blank).",
        "aliases": ["row index"],
        "field_type": "number",
    },
    "hour": {
        "label": "Hour since ICU admission",
        "detail": "Hours elapsed since ICU admission for this observation row.",
        "aliases": ["hour", "hours since admission"],
        "unit": "hours",
        "field_type": "number",
    },
    "heart_rate": {
        "label": "Heart rate",
        "detail": "Heart rate from continuous monitoring.",
        "aliases": ["heart rate", "hr", "심박수"],
        "unit": "bpm",
        "field_type": "number",
    },
    "oxygen_saturation": {
        "label": "Oxygen saturation (SpO₂)",
        "detail": "Peripheral oxygen saturation from a pulse oximeter.",
        "aliases": ["spo2", "oxygen saturation", "산소포화도"],
        "unit": "%",
        "field_type": "number",
    },
    "body_temperature": {
        "label": "Body temperature",
        "detail": "Core or skin body temperature.",
        "aliases": ["temperature", "body temperature", "체온"],
        "unit": "°C",
        "field_type": "number",
    },
    "systolic_bp": {
        "label": "Systolic blood pressure",
        "detail": "The upper number in a blood pressure reading.",
        "aliases": ["systolic", "수축기혈압"],
        "unit": "mmHg",
        "field_type": "number",
    },
    "map": {
        "label": "Mean arterial pressure",
        "detail": "Average arterial pressure across one cardiac cycle.",
        "aliases": ["map", "mean arterial pressure"],
        "unit": "mmHg",
        "field_type": "number",
    },
    "diastolic_bp": {
        "label": "Diastolic blood pressure",
        "detail": "The lower number in a blood pressure reading.",
        "aliases": ["diastolic", "이완기혈압"],
        "unit": "mmHg",
        "field_type": "number",
    },
    "respiratory_rate": {
        "label": "Respiratory rate",
        "detail": "Breaths per minute.",
        "aliases": ["respiratory rate", "breaths per minute", "호흡수"],
        "unit": "breaths/min",
        "field_type": "number",
    },
    "etco2": {
        "label": "End-tidal CO₂",
        "detail": "End-tidal carbon dioxide partial pressure.",
        "aliases": ["etco2", "end tidal co2"],
        "unit": "mmHg",
        "field_type": "number",
    },
    "baseexcess": {
        "label": "Base excess",
        "detail": "Arterial blood-gas base excess.",
        "aliases": ["base excess"],
        "unit": "mEq/L",
        "field_type": "number",
    },
    "hco3": {
        "label": "Bicarbonate (HCO₃⁻)",
        "detail": "Serum bicarbonate level from an arterial blood gas.",
        "aliases": ["bicarbonate", "hco3"],
        "unit": "mmol/L",
        "field_type": "number",
    },
    "fio2": {
        "label": "FiO₂",
        "detail": "Fraction of inspired oxygen (room air ≈ 0.21).",
        "aliases": ["fio2", "fraction inspired oxygen"],
        "unit": "fraction",
        "field_type": "number",
    },
    "ph": {
        "label": "Arterial pH",
        "detail": "Arterial blood pH from an arterial blood gas.",
        "aliases": ["ph", "arterial ph"],
        "unit": "pH",
        "field_type": "number",
    },
    "paco2": {
        "label": "PaCO₂",
        "detail": "Partial pressure of arterial CO₂ from a blood gas.",
        "aliases": ["paco2", "arterial co2"],
        "unit": "mmHg",
        "field_type": "number",
    },
    "oxygen_saturation.1": {
        "label": "Oxygen saturation (secondary)",
        "detail": "Secondary SpO₂ measurement column in the source dataset.",
        "aliases": ["oxygen saturation 2"],
        "unit": "%",
        "field_type": "number",
    },
    "ast": {
        "label": "AST",
        "detail": "Aspartate aminotransferase (AST / SGOT) liver enzyme.",
        "aliases": ["ast", "sgot"],
        "unit": "IU/L",
        "field_type": "number",
    },
    "bun": {
        "label": "Blood urea nitrogen (BUN)",
        "detail": "Kidney function marker from a basic metabolic panel.",
        "aliases": ["bun", "blood urea nitrogen"],
        "unit": "mg/dL",
        "field_type": "number",
    },
    "alkalinephos": {
        "label": "Alkaline phosphatase",
        "detail": "Liver / biliary enzyme.",
        "aliases": ["alp", "alkaline phosphatase"],
        "unit": "IU/L",
        "field_type": "number",
    },
    "calcium": {
        "label": "Serum calcium",
        "detail": "Total calcium from a basic metabolic panel.",
        "aliases": ["calcium", "Ca"],
        "unit": "mg/dL",
        "field_type": "number",
    },
    "chloride": {
        "label": "Serum chloride",
        "detail": "Chloride from a basic metabolic panel.",
        "aliases": ["chloride", "Cl"],
        "unit": "mmol/L",
        "field_type": "number",
    },
    "creatinine": {
        "label": "Serum creatinine",
        "detail": "Kidney function marker from a basic metabolic panel.",
        "aliases": ["creatinine", "serum creatinine", "크레아티닌"],
        "unit": "mg/dL",
        "field_type": "number",
    },
    "bilirubin_direct": {
        "label": "Direct bilirubin",
        "detail": "Direct (conjugated) bilirubin.",
        "aliases": ["direct bilirubin", "dbil"],
        "unit": "mg/dL",
        "field_type": "number",
    },
    "glucose": {
        "label": "Plasma glucose",
        "detail": "Plasma glucose from a basic metabolic panel.",
        "aliases": ["glucose", "blood sugar", "혈당"],
        "unit": "mg/dL",
        "field_type": "number",
    },
    "lactate": {
        "label": "Lactate",
        "detail": "Arterial lactate — elevated in sepsis and tissue hypoperfusion.",
        "aliases": ["lactate", "lactic acid", "젖산"],
        "unit": "mmol/L",
        "field_type": "number",
    },
    "magnesium": {
        "label": "Serum magnesium",
        "detail": "Magnesium from a basic metabolic panel.",
        "aliases": ["magnesium", "Mg"],
        "unit": "mg/dL",
        "field_type": "number",
    },
    "phosphate": {
        "label": "Serum phosphate",
        "detail": "Phosphate from a basic metabolic panel.",
        "aliases": ["phosphate", "phosphorus", "P"],
        "unit": "mg/dL",
        "field_type": "number",
    },
    "potassium": {
        "label": "Serum potassium",
        "detail": "Potassium from a basic metabolic panel.",
        "aliases": ["potassium", "K"],
        "unit": "mEq/L",
        "field_type": "number",
    },
    "bilirubin_total": {
        "label": "Total bilirubin",
        "detail": "Total bilirubin from a liver function blood panel.",
        "aliases": ["total bilirubin", "tbil"],
        "unit": "mg/dL",
        "field_type": "number",
    },
    "troponini": {
        "label": "Troponin I",
        "detail": "Cardiac troponin I — marker of myocardial injury.",
        "aliases": ["troponin i", "troponin"],
        "unit": "ng/mL",
        "field_type": "number",
    },
    "hct": {
        "label": "Hematocrit",
        "detail": "Percentage of red blood cells in the blood from a CBC.",
        "aliases": ["hct", "hematocrit"],
        "unit": "%",
        "field_type": "number",
    },
    "hemoglobin": {
        "label": "Hemoglobin",
        "detail": "Hemoglobin from a CBC.",
        "aliases": ["hemoglobin", "hgb", "헤모글로빈"],
        "unit": "g/dL",
        "field_type": "number",
    },
    "ptt": {
        "label": "Partial thromboplastin time",
        "detail": "Coagulation time from a coagulation panel.",
        "aliases": ["ptt", "partial thromboplastin time"],
        "unit": "seconds",
        "field_type": "number",
    },
    "wbc_count": {
        "label": "White blood cell count",
        "detail": "Leukocyte count from a CBC. Often elevated in sepsis.",
        "aliases": ["wbc", "white blood cell count", "백혈구"],
        "unit": "×10⁹/L",
        "field_type": "number",
    },
    "fibrinogen": {
        "label": "Fibrinogen",
        "detail": "Coagulation factor from a coagulation panel.",
        "aliases": ["fibrinogen"],
        "unit": "mg/dL",
        "field_type": "number",
    },
    "platelet_count": {
        "label": "Platelet count",
        "detail": "Platelets from a CBC.",
        "aliases": ["platelets", "platelet count", "혈소판"],
        "unit": "×10⁹/L",
        "field_type": "number",
    },
    "age": {
        "label": "Age",
        "detail": "Current age in years.",
        "aliases": ["age", "나이"],
        "unit": "years",
        "field_type": "number",
    },
    "gender": {
        "label": "Sex (male)",
        "detail": "1 if the patient is male, 0 otherwise.",
        "aliases": ["gender", "sex"],
        "field_type": "yes_no",
    },
    "unit1": {
        "label": "ICU unit 1 (admin flag)",
        "detail": "Administrative ICU-unit indicator from the source dataset (not clinically meaningful).",
        "aliases": ["unit1"],
        "field_type": "yes_no",
    },
    "unit2": {
        "label": "ICU unit 2 (admin flag)",
        "detail": "Administrative ICU-unit indicator from the source dataset (not clinically meaningful).",
        "aliases": ["unit2"],
        "field_type": "yes_no",
    },
    "hospadmtime": {
        "label": "Hours from hospital admission",
        "detail": "Hours between hospital admission and ICU admission (negative if ICU first).",
        "aliases": ["hospadmtime"],
        "unit": "hours",
        "field_type": "number",
    },
    "iculos": {
        "label": "ICU length of stay (so far)",
        "detail": "Current length of ICU stay at this observation.",
        "aliases": ["iculos", "icu length of stay"],
        "unit": "hours",
        "field_type": "number",
    },
    "patient_id": {
        "label": "Patient ID",
        "detail": "Internal record identifier (not clinically meaningful — leave blank).",
        "aliases": ["patient id", "record id"],
        "field_type": "number",
    },
}

_SEPSISAGENT_CONFIG = AgentConfig(
    agent_name="predict_sepsis",
    description=(
        "Binary classifier for sepsis onset from a PhysioNet-style ICU "
        "observation row. Inputs are routine vital signs, blood gas, "
        "metabolic / liver / coagulation labs, and administrative ICU "
        "context features."
    ),
    version="1.0.0-auto",
    artifact_path=_ARTIFACT_PATH,
    feature_names=['Unnamed: 0', 'hour', 'heart_rate', 'oxygen_saturation', 'body_temperature', 'systolic_bp', 'map', 'diastolic_bp', 'respiratory_rate', 'etco2', 'baseexcess', 'hco3', 'fio2', 'ph', 'paco2', 'oxygen_saturation.1', 'ast', 'bun', 'alkalinephos', 'calcium', 'chloride', 'creatinine', 'bilirubin_direct', 'glucose', 'lactate', 'magnesium', 'phosphate', 'potassium', 'bilirubin_total', 'troponini', 'hct', 'hemoglobin', 'ptt', 'wbc_count', 'fibrinogen', 'platelet_count', 'age', 'gender', 'unit1', 'unit2', 'hospadmtime', 'iculos', 'patient_id'],
    target_classes=['no_sepsis', 'sepsis'],
    trained_on_desc="PhysioNet-style ICU sepsis dataset (dataset.csv) — XGBoost K-fold ensemble",
    feature_metadata=_FEATURE_METADATA,
    n_splits=5
)

# --- 2. MCP Server Agent Class ---
class SepsisAgent(DynamicMLAgent):
    """Dynamic binary classifier for sepsis onset."""

    def __init__(self) -> None:
        super().__init__(_SEPSISAGENT_CONFIG)

    def sample_inputs(self) -> dict[str, Any]:
        """A representative sample case extracted during the build process."""
        return {
        "Unnamed:_0": 0.0,
        "hour": 0.0,
        "heart_rate": 83.5,
        "oxygen_saturation": 98.0,
        "body_temperature": 37.0,
        "systolic_bp": 121.0,
        "map": 80.0,
        "diastolic_bp": 62.0,
        "respiratory_rate": 18.0,
        "etco2": 33.0,
        "baseexcess": 0.0,
        "hco3": 24.0,
        "fio2": 0.5,
        "ph": 7.38,
        "paco2": 40.0,
        "oxygen_saturation.1": 97.0,
        "ast": 41.0,
        "bun": 17.0,
        "alkalinephos": 74.0,
        "calcium": 8.3,
        "chloride": 106.0,
        "creatinine": 0.94,
        "bilirubin_direct": 0.445,
        "glucose": 127.0,
        "lactate": 1.8,
        "magnesium": 2.0,
        "phosphate": 3.3,
        "potassium": 4.1,
        "bilirubin_total": 0.9,
        "troponini": 0.3,
        "hct": 30.3,
        "hemoglobin": 10.3,
        "ptt": 32.4,
        "wbc_count": 10.3,
        "fibrinogen": 250.0,
        "platelet_count": 181.0,
        "age": 68.54,
        "gender": 0.0,
        "unit1": 0.0,
        "unit2": 1.0,
        "hospadmtime": -0.02,
        "iculos": 1.0,
        "patient_id": 17072.0
        }
