"""Autogenerated ML Agent wrapper for StrokeAgent.

This file was generated by the CSV Builder Script from
healthcare_dataset_stroke_data.csv. Feature metadata and clinical
class labels were authored by hand after generation — do not regenerate
this file without preserving them.
"""

from pathlib import Path
from typing import Any

from services.ml_mcp_server.models._agent_factory import AgentConfig, DynamicMLAgent

# --- 1. Paths & Configuration ---
_ARTIFACT_PATH = Path(__file__).parent.parent / "artifacts" / "stroke_xgb_dynamic.joblib"

_FEATURE_METADATA: dict[str, dict[str, Any]] = {
    "patient_id": {
        "label": "Patient ID",
        "detail": "Internal record identifier (not clinically meaningful — leave blank).",
        "aliases": ["patient id", "record id"],
        "field_type": "number",
    },
    "age": {
        "label": "Age",
        "detail": "Current age in years.",
        "aliases": ["age", "나이", "살", "세"],
        "unit": "years",
        "field_type": "number",
    },
    "hypertension": {
        "label": "Hypertension",
        "detail": "Whether the patient has been diagnosed with high blood pressure (1 = yes, 0 = no).",
        "aliases": ["hypertension", "high blood pressure", "고혈압"],
        "field_type": "yes_no",
    },
    "heart_disease": {
        "label": "Heart disease",
        "detail": "Whether the patient has been diagnosed with heart disease (1 = yes, 0 = no).",
        "aliases": ["heart disease", "심장질환"],
        "field_type": "yes_no",
    },
    "glucose": {
        "label": "Average glucose",
        "detail": "Average glucose level in the blood across recent measurements.",
        "aliases": ["glucose", "average glucose", "혈당"],
        "unit": "mg/dL",
        "field_type": "number",
    },
    "bmi": {
        "label": "BMI",
        "detail": "Body mass index.",
        "aliases": ["bmi", "body mass index", "체질량지수"],
        "unit": "kg/m²",
        "field_type": "number",
    },
    "gender_Male": {
        "label": "Sex: Male",
        "detail": "1 if the patient is male, 0 otherwise.",
        "aliases": ["male", "gender male", "남성"],
        "field_type": "yes_no",
    },
    "gender_Other": {
        "label": "Sex: Other",
        "detail": "1 if the patient's recorded sex is 'other', 0 otherwise.",
        "aliases": ["gender other", "기타 성별"],
        "field_type": "yes_no",
    },
    "ever_married_Yes": {
        "label": "Ever married",
        "detail": "1 if the patient has ever been married, 0 otherwise.",
        "aliases": ["ever married", "혼인"],
        "field_type": "yes_no",
    },
    "work_type_Never_worked": {
        "label": "Work: Never worked",
        "detail": "1 if the patient has never worked, 0 otherwise.",
        "aliases": ["never worked"],
        "field_type": "yes_no",
    },
    "work_type_Private": {
        "label": "Work: Private sector",
        "detail": "1 if the patient works in the private sector, 0 otherwise.",
        "aliases": ["private work", "사기업"],
        "field_type": "yes_no",
    },
    "work_type_Self-employed": {
        "label": "Work: Self-employed",
        "detail": "1 if the patient is self-employed, 0 otherwise.",
        "aliases": ["self employed", "자영업"],
        "field_type": "yes_no",
    },
    "work_type_children": {
        "label": "Work: Child / student",
        "detail": "1 if the record is a child (still a minor or in school), 0 otherwise.",
        "aliases": ["child", "student"],
        "field_type": "yes_no",
    },
    "residence_type_Urban": {
        "label": "Residence: Urban",
        "detail": "1 if the patient lives in an urban area, 0 if rural.",
        "aliases": ["urban", "도시"],
        "field_type": "yes_no",
    },
    "smoking_status_formerly smoked": {
        "label": "Smoking: Former smoker",
        "detail": "1 if the patient is a former smoker, 0 otherwise.",
        "aliases": ["former smoker", "전 흡연자"],
        "field_type": "yes_no",
    },
    "smoking_status_never smoked": {
        "label": "Smoking: Never smoked",
        "detail": "1 if the patient has never smoked, 0 otherwise.",
        "aliases": ["never smoked", "비흡연"],
        "field_type": "yes_no",
    },
    "smoking_status_smokes": {
        "label": "Smoking: Current smoker",
        "detail": "1 if the patient currently smokes, 0 otherwise.",
        "aliases": ["current smoker", "현재 흡연"],
        "field_type": "yes_no",
    },
}

_STROKEAGENT_CONFIG = AgentConfig(
    agent_name="predict_stroke",
    description=(
        "Binary classifier for stroke risk from demographic and chronic-"
        "condition indicators (age, BMI, hypertension, heart disease, "
        "average glucose, marital / work / residence / smoking status)."
    ),
    version="1.0.0-auto",
    artifact_path=_ARTIFACT_PATH,
    feature_names=['patient_id', 'age', 'hypertension', 'heart_disease', 'glucose', 'bmi', 'gender_Male', 'gender_Other', 'ever_married_Yes', 'work_type_Never_worked', 'work_type_Private', 'work_type_Self-employed', 'work_type_children', 'residence_type_Urban', 'smoking_status_formerly smoked', 'smoking_status_never smoked', 'smoking_status_smokes'],
    target_classes=['no_stroke', 'stroke'],
    trained_on_desc="healthcare_dataset_stroke_data.csv — XGBoost K-fold ensemble",
    feature_metadata=_FEATURE_METADATA,
    n_splits=5
)

# --- 2. MCP Server Agent Class ---
class StrokeAgent(DynamicMLAgent):
    """Dynamic binary classifier for stroke risk."""

    def __init__(self) -> None:
        super().__init__(_STROKEAGENT_CONFIG)

    def sample_inputs(self) -> dict[str, Any]:
        """A representative sample case extracted during the build process."""
        return {
        "patient_id": 9046.0,
        "age": 67.0,
        "hypertension": 0.0,
        "heart_disease": 1.0,
        "glucose": 228.69,
        "bmi": 36.6,
        "gender_Male": 1.0,
        "gender_Other": 0.0,
        "ever_married_Yes": 1.0,
        "work_type_Never_worked": 0.0,
        "work_type_Private": 1.0,
        "work_type_Self-employed": 0.0,
        "work_type_children": 0.0,
        "residence_type_Urban": 1.0,
        "smoking_status_formerly_smoked": 1.0,
        "smoking_status_never_smoked": 0.0,
        "smoking_status_smokes": 0.0
        }
