"""Autogenerated ML Agent wrapper for SyntheticMortalityAgent.

This file was generated by the CSV Builder Script from
synthetic_clinical_dataset.csv. Feature metadata and clinical class
labels were authored by hand after generation — do not regenerate this
file without preserving them. Shares most features with
Hypertension_xgb (same source CSV, different target).
"""

from pathlib import Path
from typing import Any

from services.ml_mcp_server.models._agent_factory import AgentConfig, DynamicMLAgent

# --- 1. Paths & Configuration ---
_ARTIFACT_PATH = Path(__file__).parent.parent / "artifacts" / "synthetic_mortality_xgb_dynamic.joblib"

_FEATURE_METADATA: dict[str, dict[str, Any]] = {
    "patient_id": {
        "label": "Patient ID",
        "detail": "Internal record identifier (not clinically meaningful — leave blank).",
        "aliases": ["patient id", "record id"],
        "field_type": "number",
    },
    "age": {
        "label": "Age",
        "detail": "Current age in years.",
        "aliases": ["age", "나이", "살", "세"],
        "unit": "years",
        "field_type": "number",
    },
    "bmi": {
        "label": "BMI",
        "detail": "Body mass index. Height and weight are enough if BMI is not already known.",
        "aliases": ["bmi", "body mass index", "체질량", "체질량지수"],
        "unit": "kg/m²",
        "field_type": "number",
    },
    "systolic_bp": {
        "label": "Systolic blood pressure",
        "detail": "The upper number in a blood pressure reading.",
        "aliases": ["systolic", "systolic bp", "수축기혈압", "윗혈압"],
        "unit": "mmHg",
        "field_type": "number",
    },
    "diastolic_bp": {
        "label": "Diastolic blood pressure",
        "detail": "The lower number in a blood pressure reading.",
        "aliases": ["diastolic", "diastolic bp", "이완기혈압", "아래혈압"],
        "unit": "mmHg",
        "field_type": "number",
    },
    "glucose": {
        "label": "Plasma glucose",
        "detail": "Recent fasting glucose, random glucose, or oral glucose tolerance test result.",
        "aliases": ["plasma glucose", "blood sugar", "glucose", "혈당", "공복혈당"],
        "unit": "mg/dL",
        "field_type": "number",
    },
    "cholesterol": {
        "label": "Total cholesterol",
        "detail": "Total cholesterol from a lipid panel blood test.",
        "aliases": ["cholesterol", "total cholesterol", "콜레스테롤"],
        "unit": "mg/dL",
        "field_type": "number",
    },
    "creatinine": {
        "label": "Serum creatinine",
        "detail": "Kidney function marker from a basic metabolic panel.",
        "aliases": ["creatinine", "serum creatinine", "크레아티닌"],
        "unit": "mg/dL",
        "field_type": "number",
    },
    "diabetes": {
        "label": "Diabetes",
        "detail": "Whether the patient has been diagnosed with diabetes (1 = yes, 0 = no).",
        "aliases": ["diabetes", "당뇨", "당뇨병"],
        "field_type": "yes_no",
    },
    "hypertension": {
        "label": "Hypertension",
        "detail": "Whether the patient has been diagnosed with hypertension (1 = yes, 0 = no).",
        "aliases": ["hypertension", "high blood pressure", "고혈압"],
        "field_type": "yes_no",
    },
    "readmission_30d": {
        "label": "30-day readmission",
        "detail": "Whether the patient was readmitted within 30 days of a prior hospitalization (1 = yes, 0 = no).",
        "aliases": ["readmission", "30 day readmission", "재입원"],
        "field_type": "yes_no",
    },
    "gender_Male": {
        "label": "Sex: Male",
        "detail": "1 if the patient is male, 0 otherwise.",
        "aliases": ["male", "gender male", "남성"],
        "field_type": "yes_no",
    },
    "gender_Other": {
        "label": "Sex: Other",
        "detail": "1 if the patient's recorded sex is 'other', 0 otherwise.",
        "aliases": ["gender other", "기타 성별"],
        "field_type": "yes_no",
    },
    "diagnosis_Normal": {
        "label": "Admission diagnosis: Normal",
        "detail": "1 if the admission diagnosis was 'Normal', 0 otherwise.",
        "aliases": ["normal admission", "정상 진단"],
        "field_type": "yes_no",
    },
    "diagnosis_Pneumonia": {
        "label": "Admission diagnosis: Pneumonia",
        "detail": "1 if the admission diagnosis was Pneumonia, 0 otherwise.",
        "aliases": ["pneumonia", "폐렴"],
        "field_type": "yes_no",
    },
    "diagnosis_Sepsis": {
        "label": "Admission diagnosis: Sepsis",
        "detail": "1 if the admission diagnosis was Sepsis, 0 otherwise.",
        "aliases": ["sepsis", "패혈증"],
        "field_type": "yes_no",
    },
}

_SYNTHETICMORTALITYAGENT_CONFIG = AgentConfig(
    agent_name="predict_inhospital_mortality",
    description=(
        "Binary classifier for in-hospital mortality risk from a synthetic "
        "clinical dataset combining demographics, vital signs, common labs, "
        "comorbidity flags, and admission-diagnosis indicators."
    ),
    version="1.0.0-auto",
    artifact_path=_ARTIFACT_PATH,
    feature_names=['patient_id', 'age', 'bmi', 'systolic_bp', 'diastolic_bp', 'glucose', 'cholesterol', 'creatinine', 'diabetes', 'hypertension', 'readmission_30d', 'gender_Male', 'gender_Other', 'diagnosis_Normal', 'diagnosis_Pneumonia', 'diagnosis_Sepsis'],
    target_classes=['survived', 'mortality'],
    trained_on_desc="synthetic_clinical_dataset.csv (synthetic) — XGBoost K-fold ensemble",
    feature_metadata=_FEATURE_METADATA,
    n_splits=5
)

# --- 2. MCP Server Agent Class ---
class SyntheticMortalityAgent(DynamicMLAgent):
    """Dynamic binary classifier for in-hospital mortality risk."""

    def __init__(self) -> None:
        super().__init__(_SYNTHETICMORTALITYAGENT_CONFIG)

    def sample_inputs(self) -> dict[str, Any]:
        """A representative sample case extracted during the build process."""
        return {
        "patient_id": 1001.0,
        "age": 63.0,
        "bmi": 24.1,
        "systolic_bp": 131.0,
        "diastolic_bp": 81.0,
        "glucose": 136.2,
        "cholesterol": 210.3,
        "creatinine": 1.04,
        "diabetes": 0.0,
        "hypertension": 0.0,
        "readmission_30d": 0.0,
        "gender_Male": 1.0,
        "gender_Other": 0.0,
        "diagnosis_Normal": 0.0,
        "diagnosis_Pneumonia": 0.0,
        "diagnosis_Sepsis": 1.0
        }
