"""Autogenerated ML Agent wrapper for Type2DiabetesAgent.

This file was generated by the CSV Builder Script from
type2_diabetes_dataset.csv. Feature metadata and clinical class labels
were authored by hand after generation — do not regenerate this file
without preserving them.
"""

from pathlib import Path
from typing import Any

from services.ml_mcp_server.models._agent_factory import AgentConfig, DynamicMLAgent

# --- 1. Paths & Configuration ---
_ARTIFACT_PATH = Path(__file__).parent.parent / "artifacts" / "type2_diabetes_xgb_dynamic.joblib"

_FEATURE_METADATA: dict[str, dict[str, Any]] = {
    "pregnancies": {
        "label": "Pregnancies",
        "detail": "Number of pregnancies, only when clinically relevant.",
        "aliases": ["pregnancies", "pregnancy count", "임신 횟수", "임신"],
        "unit": "count",
        "field_type": "number",
    },
    "age": {
        "label": "Age",
        "detail": "Current age in years.",
        "aliases": ["age", "나이", "살", "세"],
        "unit": "years",
        "field_type": "number",
    },
    "bmi": {
        "label": "BMI",
        "detail": "Body mass index. Height and weight are enough if BMI is not already known.",
        "aliases": ["bmi", "body mass index", "체질량", "체질량지수"],
        "unit": "kg/m²",
        "field_type": "number",
    },
    "systolic_bp": {
        "label": "Systolic blood pressure",
        "detail": "The upper number in a blood pressure reading.",
        "aliases": ["systolic", "systolic bp", "수축기혈압", "윗혈압"],
        "unit": "mmHg",
        "field_type": "number",
    },
    "diastolic_bp": {
        "label": "Diastolic blood pressure",
        "detail": "The lower number in a blood pressure reading.",
        "aliases": ["diastolic", "diastolic bp", "이완기혈압", "아래혈압"],
        "unit": "mmHg",
        "field_type": "number",
    },
    "diabetes_pedigree_function": {
        "label": "Diabetes pedigree score",
        "detail": "A calculated score representing the genetic / family-history risk of diabetes.",
        "aliases": ["diabetes pedigree", "family history score", "유전 점수", "가족력 점수"],
        "unit": "score",
        "field_type": "number",
    },
    "insulin": {
        "label": "Serum insulin",
        "detail": "Recent 2-hour serum insulin result.",
        "aliases": ["insulin", "serum insulin", "인슐린"],
        "unit": "μU/mL",
        "field_type": "number",
    },
    "skin_thicknessmm": {
        "label": "Skinfold thickness",
        "detail": "Triceps skinfold thickness, often unavailable outside clinical records.",
        "aliases": ["skinfold", "triceps skinfold", "피부 두께", "피부두께"],
        "unit": "mm",
        "field_type": "number",
    },
    "glucose": {
        "label": "Plasma glucose",
        "detail": "Recent fasting glucose, random glucose, or oral glucose tolerance test result.",
        "aliases": ["plasma glucose", "blood sugar", "glucose", "혈당", "공복혈당"],
        "unit": "mg/dL",
        "field_type": "number",
    },
}

_TYPE2DIABETESAGENT_CONFIG = AgentConfig(
    agent_name="predict_type2_diabetes",
    description=(
        "Binary classifier for type-2 diabetes risk from 9 metabolic and "
        "demographic features (similar feature set to the Pima Indians "
        "dataset)."
    ),
    version="1.0.0-auto",
    artifact_path=_ARTIFACT_PATH,
    feature_names=['pregnancies', 'age', 'bmi', 'systolic_bp', 'diastolic_bp', 'diabetes_pedigree_function', 'insulin', 'skin_thicknessmm', 'glucose'],
    target_classes=['no_t2dm', 't2dm'],
    trained_on_desc="type2_diabetes_dataset.csv — XGBoost K-fold ensemble",
    feature_metadata=_FEATURE_METADATA,
    n_splits=5
)

# --- 2. MCP Server Agent Class ---
class Type2DiabetesAgent(DynamicMLAgent):
    """Dynamic binary classifier for type-2 diabetes risk."""

    def __init__(self) -> None:
        super().__init__(_TYPE2DIABETESAGENT_CONFIG)

    def sample_inputs(self) -> dict[str, Any]:
        """A representative sample case extracted during the build process."""
        return {
        "pregnancies": 3.0,
        "age": 50.0,
        "bmi": 22.26376185,
        "systolic_bp": 140.0,
        "diastolic_bp": 90.0,
        "diabetes_pedigree_function": 0.0,
        "insulin": 0.0,
        "skin_thicknessmm": 317.5,
        "glucose": 146.0
        }
